[package]
name = "lib_sockdata"
authors = ["fulup@iot.bzh"]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lib_sockcan= {path= "../../canbus-rs/sockcan"}
lib_libafb= {path= "../../afb-librust/libafb"}

[lib]
name = "sockdata"
crate-type = ["lib"]
path = "src/sockdata-lib.rs"
