[workspace]
resolver = "2"

members = [
    "sockcan-data",
    "sockcan-binding",
    "dbcapi",
    "examples/model3",
    "examples/bms",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
